# Generated by Django 5.1.15 on 2026-09-25 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=255, verbose_name='Actor Email')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('resource_type', models.CharField(max_length=100, verbose_name='Resource Type')),
                ('resource_id', models.CharField(blank=True, max_length=255, verbose_name='Resource ID')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Event Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'action'], name='idx_audit_resource_action'), models.Index(fields=['timestamp'], name='idx_audit_timestamp')],
            },
        ),
    ]
