# Generated by Django 5.1.15 on 2026-09-23 15:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("brand", models.CharField(max_length=60, verbose_name="Brand / Make")),
                ("model", models.CharField(max_length=60, verbose_name="Model")),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                (
                    "license_plate",
                    models.CharField(max_length=20, unique=True, verbose_name="License Plate"),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        unique=True,
                        verbose_name="Vehicle Identification Number (VIN)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("compact", "Compact"),
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("luxury", "Luxury"),
                            ("sports", "Sports"),
                            ("van", "Van / Minivan"),
                            ("electric", "Electric"),
                        ],
                        default="sedan",
                        max_length=30,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol / Gasoline"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "All-Electric"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                ("seats", models.PositiveSmallIntegerField(default=5, verbose_name="Seats")),
                ("doors", models.PositiveSmallIntegerField(default=4, verbose_name="Doors")),
                (
                    "mileage",
                    models.PositiveIntegerField(default=0, verbose_name="Current Odometer (km/mi)"),
                ),
                ("color", models.CharField(max_length=30, verbose_name="Exterior Color")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("rented", "Rented"),
                            ("maintenance", "Under Maintenance"),
                            ("inactive", "Inactive / Decommissioned"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Daily Base Rate"
                    ),
                ),
                (
                    "weekly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Weekly Discounted Daily Rate",
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monthly Discounted Daily Rate",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Security Deposit Required",
                    ),
                ),
                (
                    "features",
                    models.JSONField(blank=True, default=list, verbose_name="Features & Amenities"),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="Image URLs & Keys"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Public Marketing Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vehicles",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["brand", "model", "-year"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_vehicle_status"),
                    models.Index(fields=["category"], name="idx_vehicle_category"),
                    models.Index(fields=["branch"], name="idx_vehicle_branch"),
                    models.Index(fields=["license_plate"], name="idx_vehicle_plate"),
                ],
            },
        ),
    ]
