# Generated by Django 5.1.15 on 2026-10-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_category_transmission_alter_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_experience',
            field=models.CharField(blank=True, default='5+ Years', max_length=50, verbose_name='Driver Experience'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_included',
            field=models.BooleanField(default=True, verbose_name='Driver Included'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, default='Rohan Kharel', max_length=100, verbose_name='Driver Name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_rate_per_km',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6, verbose_name='Fuel Rate per KM'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Verified Vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_4h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='4-Hour Rate'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_8h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='8-Hour Rate'),
        ),
    ]
