# Generated by Django 5.1.15 on 2026-09-23 15:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("customers", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(
                        db_index=True, max_length=12, unique=True, verbose_name="Reference Number"
                    ),
                ),
                (
                    "pickup_datetime",
                    models.DateTimeField(db_index=True, verbose_name="Pickup Date & Time"),
                ),
                (
                    "return_datetime",
                    models.DateTimeField(db_index=True, verbose_name="Return Date & Time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation / Payment"),
                            ("confirmed", "Confirmed Reservation"),
                            ("active", "Active Rental (Checked Out)"),
                            ("completed", "Completed & Returned"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected / Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid in Full"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Base Rental Price"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Discount Applied",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Security Deposit Required",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Payable Price"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Reservation Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="customers.customer",
                    ),
                ),
                (
                    "pickup_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pickup_bookings",
                        to="branches.branch",
                    ),
                ),
                (
                    "return_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="return_bookings",
                        to="branches.branch",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-pickup_datetime"],
            },
        ),
        migrations.CreateModel(
            name="BookingAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Add-on Name")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price"),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["vehicle", "status"], name="idx_book_veh_status"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["pickup_datetime", "return_datetime"], name="idx_book_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["customer"], name="idx_book_customer"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("return_datetime__gt", models.F("pickup_datetime"))),
                name="booking_return_after_pickup",
            ),
        ),
    ]
