# Generated by Django 5.1.15 on 2026-10-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Advance Payment Required'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Customer Email'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Customer Phone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='decoration_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marriage Decoration'),
        ),
        migrations.AddField(
            model_name='booking',
            name='decoration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Decoration Price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_location',
            field=models.CharField(blank=True, default='Pokhara', max_length=120, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Route Distance (km)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, default='Kathmandu', max_length=120, verbose_name='Pickup Location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stops',
            field=models.JSONField(blank=True, default=list, verbose_name='Intermediate Stops'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(default='one_way', max_length=30, verbose_name='Trip Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pickup_bookings', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='return_bookings', to='branches.branch'),
        ),
    ]
