# Generated by Django 5.1.15 on 2026-09-23 15:35

import uuid

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Company Name")),
                ("slug", models.SlugField(max_length=63, unique=True, verbose_name="Tenant Slug")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "timezone",
                    models.CharField(default="UTC", max_length=50, verbose_name="Timezone"),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=3, verbose_name="Currency Code"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["schema_name"], name="idx_tenant_schema_name"),
                    models.Index(fields=["slug"], name="idx_tenant_slug"),
                ],
            },
        ),
    ]
