# Generated by Django 5.1.15 on 2026-09-23 15:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True, verbose_name="Promo Code")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Off (%)"),
                            ("fixed", "Fixed Amount Off"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Discount Value"
                    ),
                ),
                (
                    "min_rental_days",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Minimum Rental Days"),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Max Uses Allowed"
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0, verbose_name="Times Used")),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="Valid From"),
                ),
                ("valid_to", models.DateTimeField(blank=True, null=True, verbose_name="Valid To")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtraAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Add-on Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price"),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[("per_day", "Per Day"), ("per_rental", "Per Rental Flat Fee")],
                        default="per_day",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Extra Add-on",
                "verbose_name_plural": "Extra Add-ons",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Season Name")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="e.g. 1.25 for +25% surge, 0.90 for -10% off-season discount",
                        max_digits=4,
                        verbose_name="Rate Multiplier",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Seasonal Rate",
                "verbose_name_plural": "Seasonal Rates",
                "ordering": ["start_date"],
            },
        ),
    ]
