# Generated by Django 5.1.15 on 2026-09-23 15:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("service_type", models.CharField(max_length=100, verbose_name="Service Type")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(verbose_name="Scheduled Start Time")),
                ("scheduled_end", models.DateTimeField(verbose_name="Scheduled Completion Time")),
                (
                    "actual_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Completion Time"
                    ),
                ),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Odometer at Service"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="Service Cost"
                    ),
                ),
                (
                    "service_center",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Service Center / Provider",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Mechanic Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "ordering": ["-scheduled_start"],
                "indexes": [
                    models.Index(fields=["vehicle", "status"], name="idx_maint_veh_status"),
                    models.Index(
                        fields=["scheduled_start", "scheduled_end"], name="idx_maint_dates"
                    ),
                ],
            },
        ),
    ]
