# Generated by Django 5.1.15 on 2026-09-23 16:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("maintenance", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceInterval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                (
                    "interval_mileage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Interval in Distance (km/mi)"
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Interval in Days"
                    ),
                ),
                ("last_service_mileage", models.PositiveIntegerField(default=0)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_intervals",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle", "service_name"],
            },
        ),
        migrations.CreateModel(
            name="TelemetryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("odometer", models.PositiveIntegerField(verbose_name="Odometer Reading")),
                (
                    "fuel_level",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Fuel Percentage"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_inspection", "Manual Inspection"),
                            ("trip_checkout", "Trip Check-Out"),
                            ("trip_checkin", "Trip Check-In"),
                            ("service", "Service / Maintenance"),
                            ("gps_tracker", "GPS Telemetry Unit"),
                        ],
                        default="manual_inspection",
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "speed_kph",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_records",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-recorded_at"], name="maintenance_vehicle_7c4c6b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "inspector_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Logical PlatformUser ID who conducted the inspection",
                        null=True,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("check_out", "Check-Out (Pre-Rental)"),
                            ("check_in", "Check-In (Post-Rental)"),
                            ("routine", "Routine Maintenance Inspection"),
                        ],
                        default="check_out",
                        max_length=20,
                    ),
                ),
                ("odometer", models.PositiveIntegerField(verbose_name="Odometer Reading")),
                (
                    "fuel_percentage",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Fuel Level (0-100%)"
                    ),
                ),
                (
                    "battery_percentage",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="EV Battery Charge (0-100%)"
                    ),
                ),
                (
                    "exterior_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Spotless / Pristine"),
                            ("good", "Clean"),
                            ("moderate", "Lightly Soiled"),
                            ("poor", "Requires Deep Detailing"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "interior_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Spotless / Pristine"),
                            ("good", "Clean"),
                            ("moderate", "Lightly Soiled"),
                            ("poor", "Requires Deep Detailing"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("has_new_damage", models.BooleanField(default=False)),
                ("damage_description", models.TextField(blank=True, null=True)),
                (
                    "damage_photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of photo URLs/keys documenting damage evidence",
                    ),
                ),
                (
                    "customer_signature",
                    models.TextField(
                        blank=True,
                        help_text="Customer digital sign-off token or SVG representation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="bookings.booking",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "inspection_type"], name="maintenance_vehicle_759369_idx"
                    ),
                    models.Index(
                        fields=["booking", "inspection_type"], name="maintenance_booking_1db16c_idx"
                    ),
                ],
            },
        ),
    ]
