# Generated by Django 5.1.15 on 2026-09-23 15:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Tenant Owner"),
                            ("admin", "Tenant Admin"),
                            ("manager", "Fleet Manager"),
                            ("staff", "Rental Desk Staff"),
                            ("accountant", "Financial Accountant"),
                            ("viewer", "Read-Only Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("invited_email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "invitation_token",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                ("invitation_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user_id__isnull", False)),
                        fields=("user_id",),
                        name="unique_user_per_tenant",
                    )
                ],
            },
        ),
    ]
