# Generated by Django 5.1.15 on 2026-09-23 16:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "active_theme",
                    models.CharField(
                        choices=[
                            ("luxury", "Luxury Concierge"),
                            ("modern", "Modern Mobility"),
                            ("classic", "Heritage Classic"),
                            ("adventure", "All-Terrain Adventure"),
                            ("urban", "Urban Pulse"),
                            ("minimal", "Pure Minimal"),
                        ],
                        default="luxury",
                        max_length=30,
                        verbose_name="Active Theme",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#D4AF37",
                        help_text="Hex code, e.g. #D4AF37 for luxury gold or #2563EB for electric blue",
                        max_length=20,
                        verbose_name="Primary Accent Color (HEX)",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#B38F26",
                        max_length=20,
                        verbose_name="Secondary Accent Color (HEX)",
                    ),
                ),
                (
                    "font_heading",
                    models.CharField(
                        default="serif",
                        help_text="'serif' (luxury/classic) or 'sans' (modern/urban/minimal)",
                        max_length=50,
                        verbose_name="Heading Font Style",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, null=True, verbose_name="Brand Logo URL")),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Concierge Support Email",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Concierge Hotline Phone"
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Hero Banner Title"
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(blank=True, null=True, verbose_name="Hero Banner Subtitle"),
                ),
                (
                    "seo_meta_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="SEO Meta Title"
                    ),
                ),
                (
                    "seo_meta_description",
                    models.TextField(blank=True, null=True, verbose_name="SEO Meta Description"),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Keywords"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Website Configuration",
                "verbose_name_plural": "Website Configurations",
            },
        ),
    ]
