# Generated by Django 5.1.15 on 2026-09-23 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Page Title')),
                ('slug', models.SlugField(help_text='Used in the storefront URL: /pages/<slug>', max_length=120, unique=True, verbose_name='URL Slug')),
                ('content', models.TextField(help_text='Supports Markdown formatting.', verbose_name='Page Content (Markdown)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('seo_title', models.CharField(blank=True, max_length=150, verbose_name='SEO Title Override')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Description Override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible on Storefront')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number appears first in the list.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='og_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='OpenGraph / Social Image URL'),
        ),
    ]
