# Generated by Django 5.1.15 on 2026-09-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_custompage_faq_websiteconfig_og_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='Display this page as a link in the storefront footer.', verbose_name='Show in Footer'),
        ),
        migrations.AddField(
            model_name='custompage',
            name='show_in_navbar',
            field=models.BooleanField(default=False, help_text='Display this page as a link in the storefront navigation bar.', verbose_name='Show in Navbar'),
        ),
    ]
