# Generated by Django 5.1.15 on 2026-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_custompage_show_in_footer_custompage_show_in_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteconfig',
            name='active_theme',
            field=models.CharField(choices=[('sajilo', 'Sajilo Rental Nepal'), ('luxury', 'Luxury Concierge'), ('modern', 'Modern Mobility'), ('classic', 'Heritage Classic'), ('adventure', 'All-Terrain Adventure'), ('urban', 'Urban Pulse'), ('minimal', 'Pure Minimal')], default='luxury', max_length=30, verbose_name='Active Theme'),
        ),
    ]
