# Generated by Django 5.1.15 on 2026-10-06 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_alter_websiteconfig_active_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Post Title')),
                ('slug', models.SlugField(help_text='Unique URL identifier for the blog post: /blog/<slug>', max_length=150, unique=True, verbose_name='URL Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Short teaser summary displayed in blog listings.', verbose_name='Excerpt')),
                ('content', models.TextField(help_text='Full post content with formatting or markdown support.', verbose_name='Post Content')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='Cover Image URL')),
                ('author_name', models.CharField(default='Sajilo Editorial Team', max_length=100, verbose_name='Author Name')),
                ('author_avatar', models.URLField(blank=True, null=True, verbose_name='Author Avatar URL')),
                ('category', models.CharField(default='Travel Guide', max_length=60, verbose_name='Category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. Nepal, Road Trips, Pokhara)', max_length=200, verbose_name='Tags')),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='Read Time (Minutes)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
