# Generated by Django 5.1.15 on 2026-09-23 16:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "recipient_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Logical UUID reference to PlatformUser in public schema",
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Booking Confirmation"),
                            ("booking_cancellation", "Booking Cancellation"),
                            ("payment_receipt", "Payment Receipt"),
                            ("payment_failure", "Payment Failure"),
                            ("pickup_reminder", "Pickup Reminder"),
                            ("return_reminder", "Return Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("security_deposit_update", "Security Deposit Update"),
                            ("team_invitation", "Team Invitation"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-App"), ("email", "Email"), ("sms", "SMS")],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contextual details (e.g. booking_id, vehicle_name, payment_id)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_email", "is_read"], name="notificatio_recipie_e80745_idx"
                    ),
                    models.Index(
                        fields=["recipient_user_id", "is_read"],
                        name="notificatio_recipie_56404e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_key",
                    models.CharField(
                        db_index=True,
                        help_text="Idempotency key for event, e.g. 'booking_confirmation:BK-837192'",
                        max_length=120,
                    ),
                ),
                ("recipient", models.EmailField(db_index=True, max_length=254)),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-App"), ("email", "Email"), ("sms", "SMS")],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_key", "recipient", "channel"),
                        name="unique_notification_event_log",
                    )
                ],
            },
        ),
    ]
