# Generated by Django 5.1.15 on 2026-09-23 15:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Branch Name")),
                ("code", models.CharField(max_length=10, verbose_name="Branch Code")),
                ("address_line1", models.CharField(max_length=255, verbose_name="Address Line 1")),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address Line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="State / Province"
                    ),
                ),
                ("postal_code", models.CharField(max_length=20, verbose_name="Postal / ZIP Code")),
                (
                    "country",
                    models.CharField(default="US", max_length=2, verbose_name="Country Code"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Phone")),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["city"], name="idx_branch_city"),
                    models.Index(fields=["code"], name="idx_branch_code"),
                ],
            },
        ),
    ]
