# Generated by Django 5.1.15 on 2026-09-23 15:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=60, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=60, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=255, verbose_name="Email Address")),
                ("phone", models.CharField(max_length=30, verbose_name="Phone Number")),
                (
                    "driver_license_number",
                    models.CharField(max_length=50, verbose_name="Driver's License Number"),
                ),
                ("license_expiry_date", models.DateField(verbose_name="License Expiry Date")),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "country",
                    models.CharField(default="US", max_length=2, verbose_name="Country Code"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Identity Verified"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="idx_customer_email"),
                    models.Index(fields=["driver_license_number"], name="idx_customer_license"),
                ],
            },
        ),
    ]
