# Generated by Django 5.1.15 on 2026-09-23 15:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityDeposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "hold_reference",
                    models.CharField(
                        blank=True,
                        help_text="Pre-auth authorization transaction or intent ID",
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("released", "Released"),
                            ("partially_captured", "Partially Captured"),
                        ],
                        db_index=True,
                        default="authorized",
                        max_length=30,
                    ),
                ),
                (
                    "captured_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "released_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for capture or release notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_deposit_hold",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("esewa", "eSewa"),
                            ("khalti", "Khalti"),
                            ("paypal", "PayPal"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Gateway event ID (e.g. evt_xxx for Stripe)",
                        max_length=255,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "status"], name="payments_we_provide_9499ca_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="unique_provider_event_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("esewa", "eSewa"),
                            ("khalti", "Khalti"),
                            ("paypal", "PayPal"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        db_index=True,
                        default="stripe",
                        max_length=30,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rental_charge", "Rental Charge"),
                            ("security_deposit", "Security Deposit Pre-Auth"),
                            ("deposit_refund", "Deposit Refund"),
                            ("damage_charge", "Damage / Extra Charge"),
                        ],
                        default="rental_charge",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("requires_action", "Requires Customer Action"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Provider gateway transaction or payment intent reference (e.g., pi_xxx, ch_xxx)",
                        max_length=255,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique client-supplied or system-generated idempotency token",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw or structured gateway response payload",
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "status"], name="payments_pa_booking_57d6de_idx"
                    ),
                    models.Index(
                        fields=["provider", "status"], name="payments_pa_provide_cc7861_idx"
                    ),
                ],
            },
        ),
    ]
